#! /bin/bash

##### Constants

TITLE="System Information for $HOSTNAME"
RIGHT_NOW=$(date +"%x %r %Z")
TIME_STAMP="Updated on $RIGHT_NOW by $USER"
PROTOCOL="http"
SECURE_PROTOCOL="https"
location=~/.local/share/nautilus/scripts

#### check options

while getopts "hl:a:n:g:" opt; do
  case $opt in
    h) echo -e "Usage :\n\e[44maddshortcut -n <nameofshortcut> -a <linkaddress>\e[0m    ==> to add links to Agile Boards\n\e[45maddshortcut -n <nameofshortcut> -l <linkaddress>\e[0m    ==> to add links to Start"  
	exit 0
    ;;
    a) if [ -z "$OPTARG" ];
	then
		echo -e "\e[31m\e[5mError Encountered\e[0m : -a | agile  parameter cannot be empty"
		exit 1
	else
		agile="$OPTARG"
		target="$OPTARG"
		foldername="Agile Boards ->"
		location=~/.local/share/nautilus/scripts/Agile\ Boards\ \-\>
	fi
    ;;
    l) if [ -z "$OPTARG" ];
        then
                echo -e "\e[31m\e[5mError Encountered\e[0m : -l | link  parameter cannot be empty"
                exit 1
        else
                link="$OPTARG"
		target="$OPTARG"
		foldername="Start ->"
		location=~/.local/share/nautilus/scripts/Start\ \-\>
        fi
    ;;
    n) if [ -z "$OPTARG" ];
	then
		echo -e "\e[31m\e[5mError Encountered\e[0m : -n | name  parameter cannot be empty"
	        exit 1
	else
		name="$OPTARG"
	fi
    ;;
    g) if [ -z "$OPTARG" ];
        then
                echo -e "\e[31m\e[5mError Encountered\e[0m : -g | google cloud  parameter cannot be empty"
                exit 1
        else
                google="$OPTARG"
		target="$OPTARG"
		foldername="Google Cloud ->"
		location=~/.local/share/nautilus/scripts/Google\ Cloud\ \-\>
        fi
    ;;
    \?) echo "Invalid option -$OPTARG" >&2
    ;;
  esac
done


if [ -z "$name" ]; then
	echo -e "\e[31m\e[5mError Encountered\e[0m : -n | name  parameter is required to create shortcut"
	exit 1
fi


##### MAIN
if [ -z "$target" ]; then
	echo -e "\e[95mWarning\e[0m : Target link not defined"
	exit 1
else
        if test "${target#*$PROTOCOL}" != "$target" || test "${target#*$SECURE_PROTOCOL}" != "$target" ; then
		echo -e "\e[32mSuccess\e[0m : Valid URL supplied with \e[95m$PROTOCOL/$SECURE_PROTOCOL\e[0m"
		text="#! /bin/bash\n\nxdg-open $target &"
		echo -e $text >> "$location/$name"
		if [ -e "$location/$name" ] ; then
			if [ -x "$location/$name" ] ; then
				echo -e "\e[32mSuccess\e[0m : Executable shortcut \e[94m$name\e[0m created at location \e[94m~/.local/share/nautilus/scripts/Agile Boards ->/\e[0m"
                                echo -e "\e[1m\e[4mHOST\e[0m : $TITLE"
				echo -e "\e[1m\e[4mEVENT\e[0m : $TIME_STAMP"
				echo -e "\e[95mInfo\e[0m : Access shorcut by right-clicking on nautilus folders \e[44mScripts => $foldername => $name\e[0m"
			else
				sudo -u $USER chmod u+x "$location/$name"
                                if [ -x "$location/$name" ]; then
                                        echo -e "\e[32mSuccess\e[0m : File $name is executable now."

                                        echo -e "\e[32mSuccess\e[0m : Executable shortcut \e[94m$name\e[0m created at location \e[94m~/.local/share/nautilus/scripts/$foldername/\e[0m"
                                        echo -e "\e[1m\e[4mHOST\e[0m : $TITLE"
                                        echo -e "\e[1m\e[4mEVENT\e[0m : $TIME_STAMP"
                                        echo -e "\e[95mInfo\e[0m : Access shorcut by right-clicking on nautilus folders \e[44mScripts => $foldername => $name\e[0m"
                                else
                                	echo -e "\e[5m\e[31mError Encountered\e[0m : 2 : File \e[94m$name\e[0m in location \e[94m~/.local/share/nautilus/scripts/$foldername/\e[0m. Unable to make file executable. Check script permissions and try again or manually set permissions."
				fi

			fi
		else
			 echo -e "\e[5m\e[31mError Encountered\e[0m : 1 : File \e[94m$name\e[0m  does not exist in location \e[94m~/.local/share/nautilus/scripts/$foldername/\e[0m. Write failure may have occured ! Check script permissions and try again."
			exit 1

		fi
	else
		echo -e "\e[5m\e[31mError Encountered\e[0m : 3 : $target is not valid address.Enter a valid URL to create shortcut"    # $substring is not in $string
                exit 1
	fi

fi




