#! /bin/bash

HOME=~

#### .local folder
if [ ! -d "$HOME/.local" ] ; then
	echo -e "\e[31mWarning\e[0m : No \e[95m.local\e[0m directory in \e[93m$HOME\e[0m"
        exit 1
else
	echo -e "\e[32mSuccess\e[0m : \e[44m.local\e[0m folder exists in \e[93m~\e[0m"
fi


#### share folder
if [ ! -d "$HOME/.local/share" ] ; then
	echo -e "\e[31mWarning\e[0m : No \e[95mshare\e[0m directory in \e[93m$HOME/.local\e[0m"
        exit 1
else
	echo -e "\e[32mSuccess\e[0m : \e[44mshare\e[0m folder exists in \e[93m~/.local\e[0m"
fi


#### nautilus folder
if [ ! -d "$HOME/.local/share/nautilus" ] ; then
        echo -e "\e[31mWarning\e[0m : No \e[95mnautilus\e[0m directory in \e[93m$HOME/.local/share\e[0m"
        exit 1
else
	echo -e "\e[32mSuccess\e[0m : \e[44mnautilus\e[0m folder exists in \e[93m~/.local/share\e[0m"
fi


#### scripts folder
if [ ! -d "$HOME/.local/share/nautilus/scripts" ] ; then 
	echo -e "\e[31mWarning\e[0m : No \e[95mscripts\e[0m directory in \e[93m$HOME/.local/share/nautilus\e[0m"
	echo -e "\e[95mInfo\e[0m : Creating folder  \e[44mscripts\e[0m"
        mkdir $HOME/.local/share/nautilus/scripts
	if [ ! -d "$HOME/.local/share/nautilus/scripts" ] ; then
		echo -e "\e[31mError Encountered\e[0m : Unable to create \e[95mscripts\e[0m directory in \e[93m$HOME/.local/share/nautilus\e[0m"
        	exit 1
	fi
else
	echo -e "\e[32mSuccess\e[0m : \e[44mscripts\e[0m folder exists in \e[93m~/.local/share/nautilus\e[0m"
fi



#### START -> folder
if [ ! -d "$HOME/.local/share/nautilus/scripts/Start ->" ] ; then
	echo -e "\e[31mWarning\e[0m : No \e[95mStart ->\e[0m directory in \e[93m$HOME/.local/share/nautilus/scripts\e[0m"
	echo -e "\e[95mInfo\e[0m : Creating folder \e[44mStart ->\e[0m"		
	mkdir $HOME/.local/share/nautilus/scripts/Start\ \-\>
	if [ ! -d "$HOME/.local/share/nautilus/scripts/Start ->" ] ; then
                echo -e "\e[31mError Encountered\e[0m : Unable to create \e[95mStart ->\e[0m directory in \e[93m$HOME/.local/share/nautilus/scripts\e[0m"
                exit 1
        fi
else
	 echo -e "\e[32mSuccess\e[0m : \e[44mStart ->\e[0m folder exists in \e[93m~/.local/share/nautilus/scripts\e[0m"
fi



#### Agile Boards -> folder
if [ ! -d "$HOME/.local/share/nautilus/scripts/Agile Boards ->" ] ; then
        echo -e "\e[31mWarning\e[0m : No \e[95mAgile Boards ->\e[0m directory in \e[93m$HOME/.local/share/nautilus/scripts\e[0m"
        echo -e "\e[95mInfo\e[0m : Creating folder \e[44mAgile Boards ->\e[0m"              
        mkdir $HOME/.local/share/nautilus/scripts/Agile\ Boards\ \-\>
        if [ ! -d "$HOME/.local/share/nautilus/scripts/Agile Boards ->" ] ; then
                echo -e "\e[31mError Encountered\e[0m : Unable to create \e[95mAgile Boards ->\e[0m directory in \e[93m$HOME/.local/share/nautilus/scripts\e[0m"
                exit 1
        fi
else
	echo -e "\e[32mSuccess\e[0m : \e[44mAgile Boards ->\e[0m folder exists in \e[93m~/.local/share/nautilus/scripts\e[0m" 

fi


echo -e "\n\n\e[95mInfo\e[0m : Any folders or scripts created in \e[44m~/.local/share/nautilus/scripts\e[0m will be available via right-click options in nautilus"
echo -e "\tUse \e[35maddshortcut\e[0m and \e[35mremoveshorcut\e[0m to add and remove links from Scripts\n\n"  
